In [1]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [2]:
df = pd.read_csv("ProcessedData.csv")
df.head

<bound method NDFrame.head of      Unnamed: 0 Province/State         Country/Region        Lat       Long  \
0             0            NaN            Afghanistan  33.000000  65.000000
1             1            NaN                Albania  41.153300  20.168300
2             2            NaN                Algeria  28.033900   1.659600
3             3            NaN                Andorra  42.506300   1.521800
4             4            NaN                 Angola -11.202700  17.873900
..          ...            ...                    ...        ...        ...
527         261            NaN  Sao Tome and Principe   0.186360   6.613081
528         262            NaN                  Yemen  15.552727  48.516388
529         263            NaN                Comoros -11.645500  43.333300
530         264            NaN             Tajikistan  38.861034  71.276093
531         265            NaN                Lesotho -29.609988  28.233608

     Cases       Date              City  Temp_Max  Humidity  Rain  Snow
0    12456  5/27/2020         deh rawud       NaN       NaN   NaN   NaN
1     1050  5/27/2020           elbasan     55.40      82.0   0.0   0.0
2     8857  5/27/2020             adrar     81.50      18.0   0.0   0.0
3      763  5/27/2020  andorra la vella     52.00      93.0   0.0   0.0
4       71  5/27/2020          camacupa     53.69      70.0   0.0   0.0
..     ...        ...               ...       ...       ...   ...   ...
527    458    5/28/20       port-gentil     78.80      88.0   0.0   0.0
528    278    5/28/20            sayyan     63.25      30.0   0.0   0.0
529     87    5/28/20            moroni     77.47      78.0   0.0   0.0
530   3563    5/28/20       karakendzha       NaN       NaN   NaN   NaN
531      2    5/28/20       thaba-tseka     36.84      80.0   0.0   0.0

[532 rows x 12 columns]>

In [3]:
df = df.dropna()
df

,Unnamed: 0,Province/State,Country/Region,Lat,Long,Cases,Date,City,Temp_Max,Humidity,Rain,Snow
8,8,Australian Capital Territory,Australia,-35.4735,149.0124,107,5/27/2020,canberra,59.00,67.0,0.0,0.0
9,9,New South Wales,Australia,-33.8688,151.2093,3090,5/27/2020,sydney,61.00,93.0,0.0,0.0
10,10,Northern Territory,Australia,-12.4634,130.8456,29,5/27/2020,palmerston,90.00,23.0,0.0,0.0
11,11,Queensland,Australia,-28.0167,153.4000,1058,5/27/2020,gold coast,77.00,77.0,0.0,0.0
12,12,South Australia,Australia,-34.9285,138.6007,440,5/27/2020,adelaide,66.99,37.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
514,248,Anguilla,United Kingdom,18.2206,-63.0686,3,5/28/20,the valley,84.20,70.0,0.0,0.0
515,249,British Virgin Islands,United Kingdom,18.4207,-64.6400,8,5/28/20,road town,82.00,89.0,0.0,0.0
521,255,"Bonaire, Sint Eustatius and Saba",Netherlands,12.1784,-68.2385,6,5/28/20,kralendijk,82.40,78.0,0.0,0.0
523,257,Falkland Islands (Malvinas),United Kingdom,-51.7963,-59.5236,13,5/28/20,ushuaia,44.60,79.0,0.0,0.0
524,258,Saint Pierre and Miquelon,France,46.8852,-56.3159,1,5/28/20,saint-pierre,71.60,53.0,0.0,0.0

In [4]:
# Bucketing eventually in next segments
df = df.drop(["Unnamed: 0", "Province/State", "Lat", "Long", "Date"], 1)
y = df["Cases"]
x = df.drop(["Cases"], 1).values

In [5]:
list_categories = df.dtypes[df.dtypes == "object"].index.tolist()
#Encoder
enc = OneHotEncoder(sparse=False)

encode_df = pd.DataFrame(enc.fit_transform(df[list_categories]))
encode_df.columns = enc.get_feature_names(list_categories)
encode_df.head()

,Country/Region_Australia,Country/Region_Canada,Country/Region_China,Country/Region_Denmark,Country/Region_France,Country/Region_Netherlands,Country/Region_United Kingdom,City_adelaide,City_baie-mahault,City_bodden town,...,City_ulverstone,City_ushuaia,City_vancouver,City_whithorn,City_xuchang,City_yaan,City_yinchuan,City_yumen,City_zhangye,City_zhuhai
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df = df.merge(encode_df, left_index=True, right_index=True).drop(list_categories,1)
df.head()

,Cases,Temp_Max,Humidity,Rain,Snow,Country/Region_Australia,Country/Region_Canada,Country/Region_China,Country/Region_Denmark,Country/Region_France,...,City_ulverstone,City_ushuaia,City_vancouver,City_whithorn,City_xuchang,City_yaan,City_yinchuan,City_yumen,City_zhangye,City_zhuhai
8,107,59.00,67.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,3090,61.00,93.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,29,90.00,23.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,1058,77.00,77.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,440,66.99,37.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
X = df.drop(["Cases"], 1).values
y = df["Cases"].values
# Train
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [8]:
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
input_count = len(X_train[0])
hidden_nodes_1 = 20
hidden_nodes_2 = 8
print(len(X_train[0]))

81

In [10]:
# Keras Sequential Model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_1, activation="relu", input_dim=input_count))
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_2, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
nn_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 20)                1640
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 168
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9
=================================================================
Total params: 1,817
Trainable params: 1,817
Non-trainable params: 0
_________________________________________________________________

In [11]:
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Train on 42 samples
Epoch 1/100
42/42 [==============================] - 0s 8ms/sample - loss: 1603.8076 - accuracy: 0.0000e+00
Epoch 2/100
42/42 [==============================] - 0s 71us/sample - loss: 1473.7761 - accuracy: 0.0000e+00
Epoch 3/100
42/42 [==============================] - 0s 71us/sample - loss: 1332.3472 - accuracy: 0.0000e+00
Epoch 4/100
42/42 [==============================] - 0s 71us/sample - loss: 1267.0933 - accuracy: 0.0000e+00
Epoch 5/100
42/42 [==============================] - 0s 48us/sample - loss: 1165.0468 - accuracy: 0.0000e+00
Epoch 6/100
42/42 [==============================] - 0s 71us/sample - loss: 1073.5961 - accuracy: 0.0000e+00
Epoch 7/100
42/42 [==============================] - 0s 71us/sample - loss: 982.5100 - accuracy: 0.0000e+00
Epoch 8/100
42/42 [==============================] - 0s 71us/sample - loss: 895.7922 - accuracy: 0.0000e+00
Epoch 9/100
42/42 [==============================] - 0s 71us/sample - loss: 816.4716 - accuracy: 0.0000e+00
Epoch 10/100
42/42 [==============================] - 0s 71us/sample - loss: 732.9918 - accuracy: 0.0000e+00
Epoch 11/100
42/42 [==============================] - 0s 71us/sample - loss: 656.2095 - accuracy: 0.0000e+00
Epoch 12/100
42/42 [==============================] - 0s 95us/sample - loss: 555.0710 - accuracy: 0.0000e+00
Epoch 13/100
42/42 [==============================] - 0s 71us/sample - loss: 500.6513 - accuracy: 0.0000e+00
Epoch 14/100
42/42 [==============================] - 0s 71us/sample - loss: 414.8775 - accuracy: 0.0000e+00
Epoch 15/100
42/42 [==============================] - 0s 71us/sample - loss: 337.0255 - accuracy: 0.0000e+00
Epoch 16/100
42/42 [==============================] - 0s 71us/sample - loss: 258.0309 - accuracy: 0.0000e+00
Epoch 17/100
42/42 [==============================] - 0s 71us/sample - loss: 184.8990 - accuracy: 0.0000e+00
Epoch 18/100
42/42 [==============================] - 0s 48us/sample - loss: 110.7746 - accuracy: 0.0000e+00
Epoch 19/100
42/42 [==============================] - 0s 48us/sample - loss: 39.8647 - accuracy: 0.0000e+00
Epoch 20/100
42/42 [==============================] - 0s 48us/sample - loss: -32.3363 - accuracy: 0.0000e+00
Epoch 21/100
42/42 [==============================] - 0s 71us/sample - loss: -102.4617 - accuracy: 0.0000e+00
Epoch 22/100
42/42 [==============================] - 0s 71us/sample - loss: -175.2162 - accuracy: 0.0000e+00
Epoch 23/100
42/42 [==============================] - 0s 48us/sample - loss: -273.5221 - accuracy: 0.0000e+00
Epoch 24/100
42/42 [==============================] - 0s 71us/sample - loss: -322.7567 - accuracy: 0.0000e+00
Epoch 25/100
42/42 [==============================] - 0s 48us/sample - loss: -407.8920 - accuracy: 0.0000e+00
Epoch 26/100
42/42 [==============================] - 0s 71us/sample - loss: -489.4152 - accuracy: 0.0000e+00
Epoch 27/100
42/42 [==============================] - 0s 71us/sample - loss: -567.9551 - accuracy: 0.0000e+00
Epoch 28/100
42/42 [==============================] - 0s 71us/sample - loss: -692.4047 - accuracy: 0.0000e+00
Epoch 29/100
42/42 [==============================] - 0s 48us/sample - loss: -755.4147 - accuracy: 0.0000e+00
Epoch 30/100
42/42 [==============================] - 0s 71us/sample - loss: -902.1587 - accuracy: 0.0000e+00
Epoch 31/100
42/42 [==============================] - 0s 71us/sample - loss: -974.4380 - accuracy: 0.0000e+00
Epoch 32/100
42/42 [==============================] - 0s 71us/sample - loss: -1138.3060 - accuracy: 0.0000e+00
Epoch 33/100
42/42 [==============================] - 0s 71us/sample - loss: -1192.5020 - accuracy: 0.0000e+00
Epoch 34/100
42/42 [==============================] - 0s 71us/sample - loss: -1284.1725 - accuracy: 0.0000e+00
Epoch 35/100
42/42 [==============================] - 0s 71us/sample - loss: -1374.3075 - accuracy: 0.0000e+00
Epoch 36/100
42/42 [==============================] - 0s 71us/sample - loss: -1491.7647 - accuracy: 0.0000e+00
Epoch 37/100
42/42 [==============================] - 0s 71us/sample - loss: -1554.9507 - accuracy: 0.0000e+00
Epoch 38/100
42/42 [==============================] - 0s 48us/sample - loss: -1690.8785 - accuracy: 0.0000e+00
Epoch 39/100
42/42 [==============================] - 0s 48us/sample - loss: -1759.4873 - accuracy: 0.0000e+00
Epoch 40/100
42/42 [==============================] - 0s 71us/sample - loss: -1868.7318 - accuracy: 0.0238
Epoch 41/100
42/42 [==============================] - 0s 71us/sample - loss: -2013.9712 - accuracy: 0.0238
Epoch 42/100
42/42 [==============================] - 0s 71us/sample - loss: -2086.4114 - accuracy: 0.0238
Epoch 43/100
42/42 [==============================] - 0s 48us/sample - loss: -2252.9711 - accuracy: 0.0238
Epoch 44/100
42/42 [==============================] - 0s 48us/sample - loss: -2369.1872 - accuracy: 0.0238
Epoch 45/100
42/42 [==============================] - 0s 48us/sample - loss: -2451.6667 - accuracy: 0.0238
Epoch 46/100
42/42 [==============================] - 0s 48us/sample - loss: -2582.0248 - accuracy: 0.0238
Epoch 47/100
42/42 [==============================] - 0s 71us/sample - loss: -2710.6941 - accuracy: 0.0238
Epoch 48/100
42/42 [==============================] - 0s 71us/sample - loss: -2837.5268 - accuracy: 0.0238
Epoch 49/100
42/42 [==============================] - 0s 71us/sample - loss: -2999.8570 - accuracy: 0.0238
Epoch 50/100
42/42 [==============================] - 0s 71us/sample - loss: -3087.6102 - accuracy: 0.0238
Epoch 51/100
42/42 [==============================] - 0s 48us/sample - loss: -3232.6023 - accuracy: 0.0238
Epoch 52/100
42/42 [==============================] - 0s 48us/sample - loss: -3380.4413 - accuracy: 0.0238
Epoch 53/100
42/42 [==============================] - 0s 71us/sample - loss: -3532.1779 - accuracy: 0.0238
Epoch 54/100
42/42 [==============================] - 0s 71us/sample - loss: -3720.8910 - accuracy: 0.0238
Epoch 55/100
42/42 [==============================] - 0s 71us/sample - loss: -3829.3373 - accuracy: 0.0238
Epoch 56/100
42/42 [==============================] - 0s 71us/sample - loss: -3985.1021 - accuracy: 0.0238
Epoch 57/100
42/42 [==============================] - 0s 71us/sample - loss: -4197.1357 - accuracy: 0.0238
Epoch 58/100
42/42 [==============================] - 0s 71us/sample - loss: -4312.2185 - accuracy: 0.0238
Epoch 59/100
42/42 [==============================] - 0s 71us/sample - loss: -4513.0430 - accuracy: 0.0238
Epoch 60/100
42/42 [==============================] - 0s 71us/sample - loss: -4701.7757 - accuracy: 0.0238
Epoch 61/100
42/42 [==============================] - 0s 48us/sample - loss: -4882.5286 - accuracy: 0.0238
Epoch 62/100
42/42 [==============================] - 0s 71us/sample - loss: -5058.8986 - accuracy: 0.0238
Epoch 63/100
42/42 [==============================] - 0s 71us/sample - loss: -5240.7069 - accuracy: 0.0238
Epoch 64/100
42/42 [==============================] - 0s 71us/sample - loss: -5426.8036 - accuracy: 0.0238
Epoch 65/100
42/42 [==============================] - 0s 71us/sample - loss: -5672.9982 - accuracy: 0.0238
Epoch 66/100
42/42 [==============================] - 0s 71us/sample - loss: -5810.8081 - accuracy: 0.0238
Epoch 67/100
42/42 [==============================] - 0s 48us/sample - loss: -6107.9849 - accuracy: 0.0238
Epoch 68/100
42/42 [==============================] - 0s 48us/sample - loss: -6264.7107 - accuracy: 0.0238
Epoch 69/100
42/42 [==============================] - 0s 71us/sample - loss: -6535.8495 - accuracy: 0.0238
Epoch 70/100
42/42 [==============================] - 0s 95us/sample - loss: -6788.7212 - accuracy: 0.0238
Epoch 71/100
42/42 [==============================] - 0s 71us/sample - loss: -7028.0613 - accuracy: 0.0238
Epoch 72/100
42/42 [==============================] - 0s 71us/sample - loss: -7293.2857 - accuracy: 0.0238
Epoch 73/100
42/42 [==============================] - 0s 71us/sample - loss: -7532.7824 - accuracy: 0.0238
Epoch 74/100
42/42 [==============================] - 0s 71us/sample - loss: -7791.2318 - accuracy: 0.0238
Epoch 75/100
42/42 [==============================] - 0s 48us/sample - loss: -8048.2656 - accuracy: 0.0238
Epoch 76/100

42/42 [==============================] - 0s 48us/sample - loss: -8382.9071 - accuracy: 0.0238
Epoch 77/100
42/42 [==============================] - 0s 71us/sample - loss: -8578.2019 - accuracy: 0.0238
Epoch 78/100
42/42 [==============================] - 0s 71us/sample - loss: -8998.4401 - accuracy: 0.0238
Epoch 79/100
42/42 [==============================] - 0s 71us/sample - loss: -9205.3144 - accuracy: 0.0238
Epoch 80/100
42/42 [==============================] - 0s 71us/sample - loss: -9563.7983 - accuracy: 0.0238
Epoch 81/100
42/42 [==============================] - 0s 48us/sample - loss: -9906.0626 - accuracy: 0.0238
Epoch 82/100
42/42 [==============================] - 0s 71us/sample - loss: -10364.3977 - accuracy: 0.0238
Epoch 83/100
42/42 [==============================] - 0s 71us/sample - loss: -10587.3452 - accuracy: 0.0238
Epoch 84/100
42/42 [==============================] - 0s 71us/sample - loss: -10974.3020 - accuracy: 0.0238
Epoch 85/100
42/42 [==============================] - 0s 48us/sample - loss: -11350.6863 - accuracy: 0.0238
Epoch 86/100
42/42 [==============================] - 0s 48us/sample - loss: -11712.5054 - accuracy: 0.0238
Epoch 87/100
42/42 [==============================] - 0s 71us/sample - loss: -12073.4639 - accuracy: 0.0238
Epoch 88/100
42/42 [==============================] - 0s 71us/sample - loss: -12420.3871 - accuracy: 0.0238
Epoch 89/100
42/42 [==============================] - 0s 71us/sample - loss: -12777.5167 - accuracy: 0.0238
Epoch 90/100
42/42 [==============================] - 0s 71us/sample - loss: -13143.6345 - accuracy: 0.0238
Epoch 91/100
42/42 [==============================] - 0s 71us/sample - loss: -13609.9715 - accuracy: 0.0238
Epoch 92/100
42/42 [==============================] - 0s 71us/sample - loss: -13883.2084 - accuracy: 0.0238
Epoch 93/100
42/42 [==============================] - 0s 71us/sample - loss: -14472.0644 - accuracy: 0.0238
Epoch 94/100
42/42 [==============================] - 0s 71us/sample - loss: -14788.6087 - accuracy: 0.0238
Epoch 95/100
42/42 [==============================] - 0s 71us/sample - loss: -15303.3200 - accuracy: 0.0238
Epoch 96/100
42/42 [==============================] - 0s 71us/sample - loss: -15957.6678 - accuracy: 0.0238
Epoch 97/100
42/42 [==============================] - 0s 48us/sample - loss: -16275.0912 - accuracy: 0.0238
Epoch 98/100
42/42 [==============================] - 0s 71us/sample - loss: -16852.5312 - accuracy: 0.0238
Epoch 99/100
42/42 [==============================] - 0s 95us/sample - loss: -17356.7280 - accuracy: 0.0238
Epoch 100/100
42/42 [==============================] - 0s 48us/sample - loss: -18055.6300 - accuracy: 0.0238