In [1]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder


from sqlalchemy import create_engine
import psycopg2 #pip install psycopg2
from config import db_password

DBEnabled = True

In [2]:
if not DBEnabled:
    print('Database disabled')
    df = pd.read_csv("ProcessedData.csv")
else:
    print('Database enabled')
    str_db = f"postgres://postgres:{db_password}@127.0.0.1:5432/Team7"
    
    engine = create_engine(str_db)
    
    df = pd.read_sql_query('select * from "Team7"',con=engine)
df.head()

Database enabled

,index,Unnamed: 0,Province/State,Country/Region,Lat,Long,Cases,Date,City,Temp_Max,Humidity,Rain,Snow
0,0,0,None,Afghanistan,33.0000,65.0000,12456,5/27/2020,deh rawud,NaN,NaN,NaN,NaN
1,1,1,None,Albania,41.1533,20.1683,1050,5/27/2020,elbasan,55.40,82.0,0.0,0.0
2,2,2,None,Algeria,28.0339,1.6596,8857,5/27/2020,adrar,81.50,18.0,0.0,0.0
3,3,3,None,Andorra,42.5063,1.5218,763,5/27/2020,andorra la vella,52.00,93.0,0.0,0.0
4,4,4,None,Angola,-11.2027,17.8739,71,5/27/2020,camacupa,53.69,70.0,0.0,0.0

In [3]:
df = df.dropna()
df

,index,Unnamed: 0,Province/State,Country/Region,Lat,Long,Cases,Date,City,Temp_Max,Humidity,Rain,Snow
8,8,8,Australian Capital Territory,Australia,-35.4735,149.0124,107,5/27/2020,canberra,59.00,67.0,0.0,0.0
9,9,9,New South Wales,Australia,-33.8688,151.2093,3090,5/27/2020,sydney,61.00,93.0,0.0,0.0
10,10,10,Northern Territory,Australia,-12.4634,130.8456,29,5/27/2020,palmerston,90.00,23.0,0.0,0.0
11,11,11,Queensland,Australia,-28.0167,153.4000,1058,5/27/2020,gold coast,77.00,77.0,0.0,0.0
12,12,12,South Australia,Australia,-34.9285,138.6007,440,5/27/2020,adelaide,66.99,37.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,514,248,Anguilla,United Kingdom,18.2206,-63.0686,3,5/28/20,the valley,84.20,70.0,0.0,0.0
515,515,249,British Virgin Islands,United Kingdom,18.4207,-64.6400,8,5/28/20,road town,82.00,89.0,0.0,0.0
521,521,255,"Bonaire, Sint Eustatius and Saba",Netherlands,12.1784,-68.2385,6,5/28/20,kralendijk,82.40,78.0,0.0,0.0
523,523,257,Falkland Islands (Malvinas),United Kingdom,-51.7963,-59.5236,13,5/28/20,ushuaia,44.60,79.0,0.0,0.0
524,524,258,Saint Pierre and Miquelon,France,46.8852,-56.3159,1,5/28/20,saint-pierre,71.60,53.0,0.0,0.0

In [4]:
# Bucketing eventually in next segments
df = df.drop(["Unnamed: 0", "Province/State", "Lat", "Long", "Date"], 1)
y = df["Cases"]
x = df.drop(["Cases"], 1).values

In [5]:
list_categories = df.dtypes[df.dtypes == "object"].index.tolist()
#Encoder
enc = OneHotEncoder(sparse=False)

encode_df = pd.DataFrame(enc.fit_transform(df[list_categories]))
encode_df.columns = enc.get_feature_names(list_categories)
encode_df.head()

,Country/Region_Australia,Country/Region_Canada,Country/Region_China,Country/Region_Denmark,Country/Region_France,Country/Region_Netherlands,Country/Region_United Kingdom,City_adelaide,City_baie-mahault,City_bodden town,...,City_ulverstone,City_ushuaia,City_vancouver,City_whithorn,City_xuchang,City_yaan,City_yinchuan,City_yumen,City_zhangye,City_zhuhai
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df = df.merge(encode_df, left_index=True, right_index=True).drop(list_categories,1)
df.head()

,index,Cases,Temp_Max,Humidity,Rain,Snow,Country/Region_Australia,Country/Region_Canada,Country/Region_China,Country/Region_Denmark,...,City_ulverstone,City_ushuaia,City_vancouver,City_whithorn,City_xuchang,City_yaan,City_yinchuan,City_yumen,City_zhangye,City_zhuhai
8,8,107,59.00,67.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,9,3090,61.00,93.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,10,29,90.00,23.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,11,1058,77.00,77.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,12,440,66.99,37.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
X = df.drop(["Cases"], 1).values
y = df["Cases"].values
# Train
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [8]:
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
input_count = len(X_train[0])
hidden_nodes_1 = 20
hidden_nodes_2 = 8
print(len(X_train[0]))

82

In [10]:
# Keras Sequential Model
nn_model = tf.keras.models.Sequential()
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_1, activation="relu", input_dim=input_count))
nn_model.add(tf.keras.layers.Dense(units=hidden_nodes_2, activation="relu"))
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))
nn_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 20)                1660
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 168
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 9
=================================================================
Total params: 1,837
Trainable params: 1,837
Non-trainable params: 0
_________________________________________________________________

In [11]:
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Train on 42 samples
Epoch 1/100
42/42 [==============================] - 0s 8ms/sample - loss: 752.9748 - accuracy: 0.0000e+00
Epoch 2/100
42/42 [==============================] - 0s 48us/sample - loss: 678.5100 - accuracy: 0.0000e+00
Epoch 3/100
42/42 [==============================] - 0s 71us/sample - loss: 547.6042 - accuracy: 0.0000e+00
Epoch 4/100
42/42 [==============================] - 0s 71us/sample - loss: 481.6973 - accuracy: 0.0000e+00
Epoch 5/100
42/42 [==============================] - 0s 71us/sample - loss: 388.0004 - accuracy: 0.0000e+00
Epoch 6/100
42/42 [==============================] - 0s 71us/sample - loss: 339.1060 - accuracy: 0.0000e+00
Epoch 7/100
42/42 [==============================] - 0s 71us/sample - loss: 295.1183 - accuracy: 0.0000e+00
Epoch 8/100
42/42 [==============================] - 0s 71us/sample - loss: 240.9278 - accuracy: 0.0000e+00
Epoch 9/100
42/42 [==============================] - 0s 71us/sample - loss: 203.4422 - accuracy: 0.0000e+00
Epoch 10/100
42/42 [==============================] - 0s 95us/sample - loss: 142.7316 - accuracy: 0.0000e+00
Epoch 11/100
42/42 [==============================] - 0s 71us/sample - loss: 103.0889 - accuracy: 0.0000e+00
Epoch 12/100
42/42 [==============================] - 0s 71us/sample - loss: 37.9340 - accuracy: 0.0000e+00
Epoch 13/100
42/42 [==============================] - 0s 71us/sample - loss: -21.0024 - accuracy: 0.0000e+00
Epoch 14/100
42/42 [==============================] - 0s 71us/sample - loss: -69.5866 - accuracy: 0.0000e+00
Epoch 15/100
42/42 [==============================] - 0s 71us/sample - loss: -128.2651 - accuracy: 0.0238
Epoch 16/100
42/42 [==============================] - 0s 71us/sample - loss: -183.2625 - accuracy: 0.0238
Epoch 17/100
42/42 [==============================] - 0s 71us/sample - loss: -273.1696 - accuracy: 0.0238
Epoch 18/100
42/42 [==============================] - 0s 48us/sample - loss: -333.2346 - accuracy: 0.0238
Epoch 19/100
42/42 [==============================] - 0s 71us/sample - loss: -419.7057 - accuracy: 0.0238
Epoch 20/100
42/42 [==============================] - 0s 71us/sample - loss: -507.2587 - accuracy: 0.0238
Epoch 21/100
42/42 [==============================] - 0s 48us/sample - loss: -594.9324 - accuracy: 0.0238
Epoch 22/100
42/42 [==============================] - 0s 48us/sample - loss: -679.1751 - accuracy: 0.0238
Epoch 23/100
42/42 [==============================] - 0s 48us/sample - loss: -837.0223 - accuracy: 0.0238
Epoch 24/100
42/42 [==============================] - 0s 71us/sample - loss: -916.1317 - accuracy: 0.0238
Epoch 25/100
42/42 [==============================] - 0s 71us/sample - loss: -1064.5546 - accuracy: 0.0238
Epoch 26/100
42/42 [==============================] - 0s 95us/sample - loss: -1226.4795 - accuracy: 0.0238
Epoch 27/100
42/42 [==============================] - 0s 71us/sample - loss: -1323.6347 - accuracy: 0.0238
Epoch 28/100
42/42 [==============================] - 0s 71us/sample - loss: -1470.4921 - accuracy: 0.0238
Epoch 29/100
42/42 [==============================] - 0s 71us/sample - loss: -1590.7263 - accuracy: 0.0238
Epoch 30/100
42/42 [==============================] - 0s 71us/sample - loss: -1764.2187 - accuracy: 0.0238
Epoch 31/100
42/42 [==============================] - 0s 48us/sample - loss: -1847.2686 - accuracy: 0.0238
Epoch 32/100
42/42 [==============================] - 0s 71us/sample - loss: -2033.2697 - accuracy: 0.0238
Epoch 33/100
42/42 [==============================] - 0s 71us/sample - loss: -2138.1478 - accuracy: 0.0238
Epoch 34/100
42/42 [==============================] - 0s 71us/sample - loss: -2287.7722 - accuracy: 0.0238
Epoch 35/100
42/42 [==============================] - 0s 71us/sample - loss: -2445.5880 - accuracy: 0.0238
Epoch 36/100
42/42 [==============================] - 0s 71us/sample - loss: -2579.2292 - accuracy: 0.0238
Epoch 37/100
42/42 [==============================] - 0s 71us/sample - loss: -2726.5277 - accuracy: 0.0238
Epoch 38/100
42/42 [==============================] - 0s 71us/sample - loss: -2881.4750 - accuracy: 0.0238
Epoch 39/100
42/42 [==============================] - 0s 71us/sample - loss: -3065.9630 - accuracy: 0.0238
Epoch 40/100
42/42 [==============================] - 0s 71us/sample - loss: -3231.2273 - accuracy: 0.0238
Epoch 41/100
42/42 [==============================] - 0s 71us/sample - loss: -3380.4078 - accuracy: 0.0238
Epoch 42/100
42/42 [==============================] - 0s 71us/sample - loss: -3603.5471 - accuracy: 0.0238
Epoch 43/100
42/42 [==============================] - 0s 71us/sample - loss: -3882.2897 - accuracy: 0.0238
Epoch 44/100
42/42 [==============================] - 0s 71us/sample - loss: -4047.6654 - accuracy: 0.0238
Epoch 45/100
42/42 [==============================] - 0s 71us/sample - loss: -4286.2943 - accuracy: 0.0238
Epoch 46/100
42/42 [==============================] - 0s 71us/sample - loss: -4529.1600 - accuracy: 0.0238
Epoch 47/100
42/42 [==============================] - 0s 48us/sample - loss: -4749.3010 - accuracy: 0.0238
Epoch 48/100
42/42 [==============================] - 0s 48us/sample - loss: -4981.0469 - accuracy: 0.0238
Epoch 49/100
42/42 [==============================] - 0s 71us/sample - loss: -5276.4605 - accuracy: 0.0238
Epoch 50/100
42/42 [==============================] - 0s 71us/sample - loss: -5444.2716 - accuracy: 0.0238
Epoch 51/100
42/42 [==============================] - 0s 48us/sample - loss: -5706.0602 - accuracy: 0.0238
Epoch 52/100
42/42 [==============================] - 0s 95us/sample - loss: -5967.9494 - accuracy: 0.0238
Epoch 53/100
42/42 [==============================] - 0s 71us/sample - loss: -6216.2252 - accuracy: 0.0238
Epoch 54/100
42/42 [==============================] - 0s 71us/sample - loss: -6489.8923 - accuracy: 0.0238
Epoch 55/100
42/42 [==============================] - 0s 71us/sample - loss: -6783.2385 - accuracy: 0.0238
Epoch 56/100
42/42 [==============================] - 0s 71us/sample - loss: -7058.8891 - accuracy: 0.0238
Epoch 57/100
42/42 [==============================] - 0s 71us/sample - loss: -7348.6196 - accuracy: 0.0238
Epoch 58/100
42/42 [==============================] - 0s 71us/sample - loss: -7674.9107 - accuracy: 0.0238
Epoch 59/100
42/42 [==============================] - 0s 48us/sample - loss: -7958.9709 - accuracy: 0.0238
Epoch 60/100
42/42 [==============================] - 0s 48us/sample - loss: -8284.5271 - accuracy: 0.0238
Epoch 61/100
42/42 [==============================] - 0s 71us/sample - loss: -8609.9789 - accuracy: 0.0238
Epoch 62/100
42/42 [==============================] - 0s 71us/sample - loss: -8945.8597 - accuracy: 0.0238
Epoch 63/100
42/42 [==============================] - 0s 71us/sample - loss: -9375.7334 - accuracy: 0.0238
Epoch 64/100
42/42 [==============================] - 0s 71us/sample - loss: -9628.4101 - accuracy: 0.0238
Epoch 65/100
42/42 [==============================] - 0s 71us/sample - loss: -10025.8724 - accuracy: 0.0238
Epoch 66/100
42/42 [==============================] - 0s 71us/sample - loss: -10436.9096 - accuracy: 0.0238
Epoch 67/100
42/42 [==============================] - 0s 71us/sample - loss: -10965.8371 - accuracy: 0.0238
Epoch 68/100
42/42 [==============================] - 0s 71us/sample - loss: -11245.2076 - accuracy: 0.0238
Epoch 69/100
42/42 [==============================] - 0s 71us/sample - loss: -11859.8730 - accuracy: 0.0238
Epoch 70/100
42/42 [==============================] - 0s 48us/sample - loss: -12354.8586 - accuracy: 0.0238
Epoch 71/100
42/42 [==============================] - 0s 71us/sample - loss: -12709.3465 - accuracy: 0.0238
Epoch 72/100
42/42 [==============================] - 0s 71us/sample - loss: -13437.3592 - accuracy: 0.0238
Epoch 73/100
42/42 [==============================] - 0s 71us/sample - loss: -13802.6354 - accuracy: 0.0238
Epoch 74/100
42/42 [==============================] - 0s 48us/sample - loss: -14373.2461 - accuracy: 0.0238
Epoch 75/100
42/42 [==============================] - 0s 48us/sample - loss: -14920.5341 - accuracy: 0.0238
Epoch 76/100
42/42 [==============================] - 0s 71us/sample - loss: -15609.9390 - accuracy: 0.0238
Epoch 77/100

42/42 [==============================] - 0s 71us/sample - loss: -16170.5510 - accuracy: 0.0238
Epoch 78/100
42/42 [==============================] - 0s 48us/sample - loss: -16568.4446 - accuracy: 0.0238
Epoch 79/100
42/42 [==============================] - 0s 71us/sample - loss: -17408.5551 - accuracy: 0.0238
Epoch 80/100
42/42 [==============================] - 0s 95us/sample - loss: -17841.8747 - accuracy: 0.0238
Epoch 81/100
42/42 [==============================] - 0s 71us/sample - loss: -18525.8847 - accuracy: 0.0238
Epoch 82/100
42/42 [==============================] - 0s 71us/sample - loss: -19356.4347 - accuracy: 0.0238
Epoch 83/100
42/42 [==============================] - 0s 71us/sample - loss: -20012.8657 - accuracy: 0.0238
Epoch 84/100
42/42 [==============================] - 0s 71us/sample - loss: -20550.9472 - accuracy: 0.0238
Epoch 85/100
42/42 [==============================] - 0s 71us/sample - loss: -21275.4840 - accuracy: 0.0238
Epoch 86/100
42/42 [==============================] - 0s 71us/sample - loss: -21996.7141 - accuracy: 0.0238
Epoch 87/100
42/42 [==============================] - 0s 48us/sample - loss: -22730.9405 - accuracy: 0.0238
Epoch 88/100
42/42 [==============================] - 0s 48us/sample - loss: -23391.1672 - accuracy: 0.0238
Epoch 89/100
42/42 [==============================] - 0s 71us/sample - loss: -24095.2831 - accuracy: 0.0238
Epoch 90/100
42/42 [==============================] - 0s 71us/sample - loss: -24789.2965 - accuracy: 0.0238
Epoch 91/100
42/42 [==============================] - 0s 48us/sample - loss: -25445.3537 - accuracy: 0.0238
Epoch 92/100
42/42 [==============================] - 0s 71us/sample - loss: -26362.4059 - accuracy: 0.0238
Epoch 93/100
42/42 [==============================] - 0s 71us/sample - loss: -26819.4215 - accuracy: 0.0238
Epoch 94/100
42/42 [==============================] - 0s 71us/sample - loss: -27624.3336 - accuracy: 0.0238
Epoch 95/100
42/42 [==============================] - 0s 48us/sample - loss: -28389.7203 - accuracy: 0.0238
Epoch 96/100
42/42 [==============================] - 0s 71us/sample - loss: -29143.0743 - accuracy: 0.0238
Epoch 97/100
42/42 [==============================] - 0s 71us/sample - loss: -29882.2057 - accuracy: 0.0238
Epoch 98/100
42/42 [==============================] - 0s 71us/sample - loss: -30603.1178 - accuracy: 0.0238
Epoch 99/100
42/42 [==============================] - 0s 71us/sample - loss: -31573.1737 - accuracy: 0.0238
Epoch 100/100
42/42 [==============================] - 0s 71us/sample - loss: -32098.9507 - accuracy: 0.0238